import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>WebGIS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* This the page you see when you open the  */}
      <main>
     
        <div>
          Hello world
        </div>
      </main>

    </div>
  )
}
